const $=s=>document.querySelector(s), cfg=window.BOARD_CONFIG||{}, live=!!(cfg.supabaseUrl&&cfg.supabaseKey), key='common-ground-v1';
let saved;try{saved=JSON.parse(localStorage.getItem(key))||{};}catch{saved={};}
let identity=saved.identity||{id:crypto.randomUUID(),name:''},user={id:identity.id},profile=null,db,ideas=[],votes=[],comments=[],opened=new Set();
function save(){localStorage.setItem(key,JSON.stringify({identity,ideas,votes,comments}));}
function node(tag,cls,text){const n=document.createElement(tag);n.className=cls||'';if(text!==undefined)n.textContent=text;return n;}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',5000);}
function check(r){if(r.error)throw r.error;return r.data;}
async function busy(b,fn){b.disabled=true;try{await fn();}catch(e){toast('Could not save. '+e.message);}finally{b.disabled=false;}}
function needName(){if(profile)return true;$('#login').showModal();return false;}
function showIdentity(){$('#identity').textContent=profile?`${profile.name} · change`:'Enter your name ↗';}
async function refresh(){if(live){const r=await Promise.all([db.from('ideas').select('*'),db.from('votes').select('*'),db.from('comments').select('*').order('created_at')]);[ideas,votes,comments]=r.map(check);}render();}
async function insert(table,record){if(live)check(await db.from(table).insert(record));else{({ideas,votes,comments})[table].push({...record,id:crypto.randomUUID(),created_at:new Date().toISOString()});save();}}
function render(){const feed=$('#feed');feed.replaceChildren();$('#total').textContent=ideas.length;const count=id=>votes.filter(v=>v.idea_id===id).length;
const sorted=[...ideas].sort((a,b)=>($('#sort').value==='top'?count(b.id)-count(a.id):0)||Date.parse(b.created_at)-Date.parse(a.created_at));
if(!sorted.length){const empty=node('div','empty');empty.append(node('div','ornament','✳'),node('h2','','Every project starts somewhere.'),node('p','','Share the first idea. Your group can vote, ask questions, and help it take shape.'));feed.append(empty);}
for(const idea of sorted){const card=node('article','idea'),meta=node('div','meta'),time=node('time','',new Date(idea.created_at).toLocaleDateString(undefined,{month:'short',day:'numeric'}));time.dateTime=idea.created_at;meta.append(node('span','avatar',idea.author_name.trim().split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()),node('span','',idea.author_name),time);card.append(meta,node('h3','',idea.title),node('div','idea-body',idea.body));
const related=comments.filter(c=>c.idea_id===idea.id),actions=node('div','actions'),voted=votes.some(v=>v.idea_id===idea.id&&v.user_id===user?.id),vote=node('button','vote',`↑ ${count(idea.id)} ${count(idea.id)===1?'vote':'votes'}`);vote.setAttribute('aria-pressed',String(voted));vote.setAttribute('aria-label',`${voted?'Remove vote from':'Vote for'} ${idea.title}`);
vote.onclick=()=>{if(!needName())return;busy(vote,async()=>{if(voted){if(live)check(await db.from('votes').delete().eq('idea_id',idea.id).eq('user_id',user.id));else{votes=votes.filter(v=>!(v.idea_id===idea.id&&v.user_id===user.id));save();}}else await insert('votes',{idea_id:idea.id,user_id:user.id});await refresh();});};
const toggle=node('button','comment-toggle',`${related.length} ${related.length===1?'comment':'comments'} ↗`);toggle.setAttribute('aria-expanded',String(opened.has(idea.id)));toggle.onclick=()=>{opened.has(idea.id)?opened.delete(idea.id):opened.add(idea.id);render();};actions.append(vote,toggle);card.append(actions);
if(opened.has(idea.id)){const thread=node('div','comments');for(const c of related){const item=node('div','comment');item.append(node('span','small',c.author_name),node('p','',c.body));thread.append(item);}const form=node('form','comment-form'),label=node('label','','Add to the conversation'),input=node('textarea'),submit=node('button','primary','Post comment →');input.id='comment-'+idea.id;label.htmlFor=input.id;input.rows=2;input.required=true;input.maxLength=2000;input.placeholder='Ask a question or build on the idea…';submit.type='submit';form.append(label,input,submit);input.oninput=()=>input.setCustomValidity('');form.onsubmit=e=>{e.preventDefault();if(!needName())return;const body=input.value.trim();if(!body){input.setCustomValidity('Write a comment first.');input.reportValidity();return;}busy(submit,async()=>{await insert('comments',{idea_id:idea.id,user_id:user.id,author_name:profile.name,body});await refresh();toast('Comment added.');});};thread.append(form);card.append(thread);}feed.append(card);}}
$('#identity').onclick=()=>{$('#name').value=profile?.name||'';$('#login').showModal();};$('#cancel-login').onclick=()=>$('#login').close();$('#name').oninput=()=>$('#name').setCustomValidity('');
$('#name-form').onsubmit=e=>{e.preventDefault();const name=$('#name').value.trim();if(name.length<2){$('#name').setCustomValidity('Enter at least two characters.');$('#name').reportValidity();return;}busy(e.submitter,async()=>{if(live){if(!user){user=check(await db.auth.signInAnonymously()).user;}check(await db.from('profiles').upsert({id:user.id,name}));}else{identity.name=name;save();}profile={name};showIdentity();$('#login').close();await refresh();toast(`Welcome, ${name}.`);});};
$('#body').oninput=()=>{$('#count').textContent=`${$('#body').value.length.toLocaleString()} / 4,000`;$('#body').setCustomValidity('');};$('#title').oninput=()=>$('#title').setCustomValidity('');
$('#idea-form').onsubmit=e=>{e.preventDefault();if(!needName())return;const title=$('#title').value.trim(),body=$('#body').value.trim();if(!title||!body){const input=$(title?'#body':'#title');input.setCustomValidity('Please add some text.');input.reportValidity();return;}busy(e.submitter,async()=>{await insert('ideas',{user_id:user.id,author_name:profile.name,title,body});$('#idea-form').reset();$('#count').textContent='0 / 4,000';await refresh();toast('Your idea is on the table.');});};$('#sort').onchange=render;
async function start(){$('#mode').textContent=live?'Shared group board · Enter your name to post, vote, and comment.':'Local preview · Posts, votes, and comments stay in this browser until the shared board is connected.';if(live){const {createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');db=createClient(cfg.supabaseUrl,cfg.supabaseKey);user=check(await db.auth.getSession()).session?.user;if(user)profile=check(await db.from('profiles').select('name').eq('id',user.id).maybeSingle());await refresh();}else{ideas=saved.ideas||[];votes=saved.votes||[];comments=saved.comments||[];profile=identity.name?{name:identity.name}:null;render();}showIdentity();if(!profile)$('#login').showModal();}
start().catch(e=>{$('#mode').textContent='The shared board could not connect. Reload to try again.';toast(e.message);});
setInterval(()=>{if(live&&db&&document.visibilityState==='visible'&&!$('#login').open&&!opened.size&&!document.activeElement.matches('input,textarea,button'))refresh().catch(()=>{});},30000);
